name: Manual Deploy to GCP

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Docker image version to deploy (e.g., v1.2.3 or latest)"
        required: true
        default: "latest"
      environment:
        description: "Environment to deploy to"
        required: true
        default: "production"
        type: choice
        options:
          - production

env:
  GCP_IMAGE: europe-west2-docker.pkg.dev/uk-vm-00001/resume-builder/easyfreeresume-app

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Verify image exists
        run: |
          echo "Verifying image exists: ${{ env.GCP_IMAGE }}:${{ github.event.inputs.version }}"
          echo '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}' | docker login -u _json_key_base64 --password-stdin europe-west2-docker.pkg.dev
          docker manifest inspect ${{ env.GCP_IMAGE }}:${{ github.event.inputs.version }} || {
            echo "❌ Image not found: ${{ env.GCP_IMAGE }}:${{ github.event.inputs.version }}"
            echo "Available tags can be found in GCP Artifact Registry"
            exit 1
          }

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ secrets.GCP_CLOUD_RUN_SERVICE }}
          image: ${{ env.GCP_IMAGE }}:${{ github.event.inputs.version }}
          region: "europe-west2"
          flags: |
            --cpu=1
            --memory=1Gi
            --min-instances=0
            --max-instances=10
            --concurrency=80
            --timeout=300
            --allow-unauthenticated

      - name: Deployment Summary
        run: |
          echo "🚀 **Manual Deployment Successful!**" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Service URL:** ${{ steps.deploy.outputs.url }}" >> $GITHUB_STEP_SUMMARY
          echo "**Version:** ${{ github.event.inputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "**Environment:** ${{ github.event.inputs.environment }}" >> $GITHUB_STEP_SUMMARY
          echo "**Image:** ${{ env.GCP_IMAGE }}:${{ github.event.inputs.version }}" >> $GITHUB_STEP_SUMMARY
