name: PR Validation

on:
  pull_request:
    branches:
      - main

jobs:
  changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      code-changed: ${{ steps.changes.outputs.code }}
      docs-only: ${{ steps.changes.outputs.docs-only }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Check for code changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            code:
              - 'resume-builder-ui/**'
              - 'app.py'
              - 'resume_generator*.py'
              - 'templates/**'
              - 'requirements.txt'
              - 'package*.json'
              - 'Dockerfile*'
              - '.github/workflows/**'
            docs-only:
              - '*.md'
              - 'docs/**'
              - 'LICENSE'
              - '.gitignore'

  test:
    name: Frontend Tests
    needs: changes
    if: needs.changes.outputs.code-changed == 'true'
    uses: ./.github/workflows/test-reusable.yml

  docker-build:
    name: Build Docker (Verify)
    runs-on: ubuntu-latest
    needs: [changes, test]
    if: needs.changes.outputs.code-changed == 'true' && !failure()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image (verification only)
        run: |
          docker build -t resume-builder:pr-${{ github.event.number }} .
          echo "✅ Docker build successful - image not pushed on PR"

  docs-only-check:
    name: Documentation Only
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.code-changed == 'false'
    
    steps:
      - name: Documentation change detected
        run: |
          echo "📚 Only documentation files changed - skipping tests and build"
          echo "✅ PR validation complete for docs-only changes"