name: Test Main Branch

# Run comprehensive tests when code is pushed to main
# This ensures main branch is always in a deployable state

on:
  push:
    branches: [main]

jobs:
  test-frontend:
    name: Frontend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: resume-builder-ui

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: resume-builder-ui/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run TypeScript check
        run: npm run type-check

      - name: Run tests with coverage
        run: npm run coverage

      - name: Upload frontend coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: frontend-coverage
          path: resume-builder-ui/coverage
          retention-days: 7

  # TODO: Add backend tests when available
  # test-backend:
  #   name: Backend Tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #     - name: Setup Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.13'
  #     - name: Run backend tests
  #       run: pytest

  validate-deployment:
    name: Validate Deployment Readiness
    runs-on: ubuntu-latest
    needs: [test-frontend]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for validation
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: false
          tags: validation:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test Summary
        run: |
          echo "✅ **Main Branch Tests Passed**" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Frontend Tests:** ✅ Passed" >> $GITHUB_STEP_SUMMARY
          echo "**Docker Build:** ✅ Successful" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "🚀 **Ready for Release Creation**" >> $GITHUB_STEP_SUMMARY